name: equipment_maintenance
description: "Equipment maintenance tech task"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^7.8.4
  bloc: ^8.1.3
  dart_mappable: ^4.2.0
  http: ^1.2.1
  talker: ^4.1.0
  talker_flutter: ^4.1.0
  flutter_bloc: ^8.1.3
  paged_datatable: ^2.0.0-dev.4
  meta: ^1.12.0
  rxdart: ^0.27.7
  lru_cache:
    git: https://github.com/Zekfad/lru_cache
  flutter_localizations:
    sdk: flutter
  slang: ^3.25.0
  slang_flutter: ^3.25.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  dart_mappable_builder: ^4.2.0
  auto_route_generator: ^7.3.2
  slang_build_runner: ^3.25.0

  flutter_lints: ^3.0.0

dependency_overrides:
  meta: ^1.12.0

flutter:
  uses-material-design: true